# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdzkproto/sdzkp.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sdzkproto/sdzkp.proto\x12\x05sdzkp\"\x89\x01\n\x0bSGDInstance\x12\r\n\x05sgdid\x18\x01 \x01(\t\x12\r\n\x01g\x18\x02 \x03(\x03\x42\x02\x10\x01\x12\t\n\x01n\x18\x03 \x01(\x04\x12\t\n\x01m\x18\x04 \x01(\x04\x12\x16\n\ngenerators\x18\x05 \x03(\x03\x42\x02\x10\x01\x12\x14\n\x0cmin_distance\x18\x06 \x01(\x04\x12\x18\n\x10number_of_rounds\x18\x07 \x01(\x04\".\n\x08SetupAck\x12\r\n\x05sgdid\x18\x01 \x01(\t\x12\x13\n\x0bsetupresult\x18\x02 \x01(\x08\"Q\n\x0b\x43ommitments\x12\r\n\x05sgdid\x18\x01 \x01(\t\x12\x0f\n\x07roundid\x18\x02 \x01(\x04\x12\n\n\x02\x43\x31\x18\x03 \x01(\x0c\x12\n\n\x02\x43\x32\x18\x04 \x01(\x0c\x12\n\n\x02\x43\x33\x18\x05 \x01(\x0c\">\n\tChallenge\x12\r\n\x05sgdid\x18\x01 \x01(\t\x12\x0f\n\x07roundid\x18\x02 \x01(\x04\x12\x11\n\tchallenge\x18\x03 \x01(\x03\"w\n\x08Response\x12\r\n\x05sgdid\x18\x01 \x01(\t\x12\x0f\n\x07roundid\x18\x02 \x01(\x04\x12\x0e\n\x02Z1\x18\x03 \x03(\x03\x42\x02\x10\x01\x12\x0e\n\x02Z2\x18\x04 \x03(\x03\x42\x02\x10\x01\x12\t\n\x01s\x18\x05 \x01(\x03\x12\x0f\n\x03t_r\x18\x06 \x03(\x03\x42\x02\x10\x01\x12\x0f\n\x03t_u\x18\x07 \x03(\x03\x42\x02\x10\x01\"e\n\x12VerificationResult\x12\r\n\x05sgdid\x18\x01 \x01(\t\x12\x0f\n\x07roundid\x18\x02 \x01(\x04\x12\x13\n\x0broundresult\x18\x03 \x01(\x08\x12\x1a\n\x12verificationresult\x18\x04 \x01(\x08\x32\xa1\x01\n\x05SDZKP\x12.\n\x05Setup\x12\x12.sdzkp.SGDInstance\x1a\x0f.sdzkp.SetupAck\"\x00\x12\x30\n\x06\x43ommit\x12\x12.sdzkp.Commitments\x1a\x10.sdzkp.Challenge\"\x00\x12\x36\n\x06Verify\x12\x0f.sdzkp.Response\x1a\x19.sdzkp.VerificationResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdzkproto.sdzkp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SGDINSTANCE'].fields_by_name['g']._loaded_options = None
  _globals['_SGDINSTANCE'].fields_by_name['g']._serialized_options = b'\020\001'
  _globals['_SGDINSTANCE'].fields_by_name['generators']._loaded_options = None
  _globals['_SGDINSTANCE'].fields_by_name['generators']._serialized_options = b'\020\001'
  _globals['_RESPONSE'].fields_by_name['Z1']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['Z1']._serialized_options = b'\020\001'
  _globals['_RESPONSE'].fields_by_name['Z2']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['Z2']._serialized_options = b'\020\001'
  _globals['_RESPONSE'].fields_by_name['t_r']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['t_r']._serialized_options = b'\020\001'
  _globals['_RESPONSE'].fields_by_name['t_u']._loaded_options = None
  _globals['_RESPONSE'].fields_by_name['t_u']._serialized_options = b'\020\001'
  _globals['_SGDINSTANCE']._serialized_start=33
  _globals['_SGDINSTANCE']._serialized_end=170
  _globals['_SETUPACK']._serialized_start=172
  _globals['_SETUPACK']._serialized_end=218
  _globals['_COMMITMENTS']._serialized_start=220
  _globals['_COMMITMENTS']._serialized_end=301
  _globals['_CHALLENGE']._serialized_start=303
  _globals['_CHALLENGE']._serialized_end=365
  _globals['_RESPONSE']._serialized_start=367
  _globals['_RESPONSE']._serialized_end=486
  _globals['_VERIFICATIONRESULT']._serialized_start=488
  _globals['_VERIFICATIONRESULT']._serialized_end=589
  _globals['_SDZKP']._serialized_start=592
  _globals['_SDZKP']._serialized_end=753
# @@protoc_insertion_point(module_scope)
